global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'mi-coche-ideal-api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 5s
    scrape_timeout: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 